// This file is @generated by prost-build.
/// 定义EventSpec消息
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EventSpec {
    /// 事件唯一标识符
    #[prost(string, tag = "1")]
    pub event_uuid: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub event_title: ::prost::alloc::string::String,
    /// 事件描述
    #[prost(string, tag = "3")]
    pub event_description: ::prost::alloc::string::String,
    /// 事件链接
    #[prost(string, tag = "4")]
    pub event_href: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub event_time: ::prost::alloc::string::String,
    /// 可选的图片哈希值
    #[prost(string, tag = "6")]
    pub image_hash: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventList {
    /// EventSpec 的列表
    #[prost(message, repeated, tag = "1")]
    pub events: ::prost::alloc::vec::Vec<EventSpec>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventPost {
    #[prost(string, tag = "1")]
    pub token: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub events: ::prost::alloc::vec::Vec<EventSpec>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EventDelete {
    #[prost(string, tag = "1")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub uuids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EventUpdate {
    #[prost(string, tag = "1")]
    pub token: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub event: ::core::option::Option<EventSpec>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AdminToken {
    #[prost(string, tag = "1")]
    pub token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StorageInfo {
    #[prost(uint64, tag = "1")]
    pub size: u64,
    #[prost(uint32, tag = "2")]
    pub count: u32,
    #[prost(string, repeated, tag = "3")]
    pub files: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ImageUpload {
    #[prost(string, tag = "3")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag = "1")]
    pub filename: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub image: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ImageDelete {
    #[prost(string, tag = "1")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub filename: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StateResponse {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
}
